### ISSUE TITLE
Validator reports wrong encoding errors on official OPML examples

### ISSUE THREAD

**Issue by Alkarex** [scripting/opml.org#17]
Hello,
The validator wrongly reports some encoding errors on [examples given by the OPML specification](http://opml.org/spec2.opml#1629043023000) such as http://hosting.opml.org/dave/spec/subscriptionList.opml

![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/ff44f103-a788-4f8b-988f-0a7493626fc4)

Example of supposedly wrong line (which is perfectly fine, XML compliant, and OPML compliant):

```xml
<outline text="NYT &gt; Business"
  description="Find breaking news &amp; business news on Wall Street, media &amp; advertising, international business, banking, interest rates, the stock market, currencies &amp; funds."
  htmlUrl="http://www.nytimes.com/pages/business/index.html?partner=rssnyt"
  language="unknown" title="NYT &gt; Business" type="rss" version="RSS2"
  xmlUrl="http://www.nytimes.com/services/xml/rss/nyt/Business.xml"/>
```

According to the OPML specification http://opml.org/spec2.opml#1629042276000 :

> Text attributes may contain encoded HTML markup

At a quick glance, the logic of the validator seems bogus, as it performs an [XML parsing](https://github.com/scripting/opml.org/blob/5ea01b2f0fd52867c1b476dc0fff1aa6f209a13d/opmlValidator/code.js#L272) (which is good) but then does some manual check of the [XML entities](https://github.com/scripting/opml.org/blob/5ea01b2f0fd52867c1b476dc0fff1aa6f209a13d/opmlValidator/code.js#L129-L130), forgetting that those are already handled by the XML parser...

Downstream bug report https://github.com/FreshRSS/FreshRSS/issues/6140#issuecomment-2054202910 (with additional bogus reports from the validator, left for other tickets)

**Comment by scripting** [comment]
@Alkarex -- Thanks for the report. 

The problem should be fixed.
