### ISSUE TITLE
media type for OPML?

### ISSUE THREAD

**Issue by mnot** [scripting/opml.org#2]
Hey Dave,

Do you know if people are using any particular media type for OPML -- e.g., `application/opml+xml`?

If so we should probably get it registered. If not, it'd be good to establish a convention, so that e.g., when you click on an OPML file your machine will automatically open your feed reader.

**Comment by scripting** [comment]
Hi Mark… 

we just use text/xml.

nothing new to register..

**Comment by mnot** [comment]
Hm. That's workable, but I'd really like to create an experience where someone can click on a link and have the resulting OPML dispatched automatically to their feed reader, similar to how RSS/Atom links work now.

**Comment by scripting** [comment]
@mnot -- OPML is a broadly useful format, not just feed readers, and it's 21 years old. I'm closing this issue.
