### ISSUE TITLE
Subscription list issue, type="rss" is required

### ISSUE THREAD

**Issue by scripting** [scripting/opml.org#21]
I'm writing some code that parses reading lists, and came across a case where FeedLand isn't finding any feeds in a file.

https://colinwalker.blog/feeds.opml

There are 85 `<outline>` nodes that have xmlUrls, but here's the problem, my software only looks at nodes with `type="rss"` so it's not picking up any feeds from that outline. 

Here's an example of a feed outline node.

`<outline text="Alastair Johnston" xmlUrl="https://alastairjohnston.com/feed.xml" htmlUrl="https://alastairjohnston.com/" />`

Looking at the [spec](https://opml.org/spec2.opml#1629042482000):

> A subscription list is a possibly multiple-level list of subscriptions to feeds. Each sub-element of the body of the OPML document is a node of type rss or an outline element that contains nodes of type rss.

Colin, I really appreciate your support for this format, I hope to be able to show the results of this work soon. :smile:

**Comment by colin-walker** [comment]
Thanks @scripting — I'll have a look at it tomorrow and make the required corrections, both to the OPML itself and the auto-generator.

**Comment by colin-walker** [comment]
@scripting That should be fixed now. Let me know if you spot anything else.

**Comment by scripting** [comment]
@colin-walker -- thanks for making the change, we're now getting all of your feeds. :-)
