### ISSUE TITLE
browser.blogroll.social is up

### ISSUE THREAD

**Issue by scripting** [scripting/opml.org#22]
I've been working on a project for the last couple of weeks to see what's out there in the Land of Blogrolls, since Manton and I did our little push a couple of months ago. 

https://browse.blogroll.social/

So I set out to write some software that would crawl the blogrolls I could find, starting with my blogroll, and then looking at each feed to see if I could find a blogroll linked into it.

That meant going from the htmlUrl link in an outline node and looking for a link to a blogroll. 

I found about 25 blogrolls, give or take, there were some duplicates, ie two URLs to the same list. We're going to have to figure out what to do about that. 

My software crawls the structure periodically, once every 10 minutes -- so if you make a change to your blogroll, it should be reflected pretty quickly.

I think we will feel blogrolls a lot more than they used to be. A very loose structure for network-building all outside the silos. This is what I hoped we'd be doing with OPML when it started, in 2000, now maybe we're getting there.

Since it revolves around OPML, I thought it would be good to talk about it here.

**Comment by scripting** [comment]
One thing I want to point out is that each blogroll has an address.

https://browse.blogroll.social/?blogrollUrl=https%3A%2F%2Fdanq.me%2Fblogroll.xml&blogrollTitle=Dan%20Q%27s%20Blogroll

I'm going to make that shorter, but for now that's how you can point to a specific blogroll in this context.

DanQ's blogroll is one of the best out there, btw, imho of course.

**Comment by colin-walker** [comment]
Discovery has long been an issue with blogs. We took a huge backwards step with the mass adoption of (and reliance on) social media which killed the likes of Digg and Technorati.

As I always say, what better recommendation is there than the blogs you read yourself — returning to blogrolls as a loose network can solve so many issues in such a simple way with minimal changes to a standard OPML.

**Comment by scripting** [comment]
@colin-walker -- 

i totally agree. and we can build all kinds of structures from the network of blogrolls linking to other blogrolls through the link in the HTML and RSS. 

BTW, only one feed has a link to its blogroll (mine) so I'm only using the HTML linkage to determine if a site has a blogroll.

I get to the HTML page via the htmlUrl attribute on the `<outline>` element. 

This is the kind of discovery system I wished we had in place in 2000 when we first started using OPML. But we're here now, and there's enough of a beginning to perhaps start a bootstrap that grows like blogs did, then feeds, then podcasts.

It make a huge difference that Manton is working on this too, btw.

**Comment by scripting** [comment]
I did some work on cosmetics this morning. 

https://browse.blogroll.social/

1. The title of the page changed from We Heart Blogrolls to Blogroll Browser.

2. The columns line up better. 

3. There's a link to this thread in the explainer.

I'm starting to think about linking up to other behind-the-scenes resources. 

For example, there's a fresh instance of FeedLand running behind this, so all the blogrolls are also reading lists, and they have associated rivers. That should all work (haven't looked yet). 

1. We have to get titles on all the OPML files. That's the first thing @colin-walker noticed. 

2. Why is Manton's list showing up twice.

3. I want people to see this. I haven't posted it on Scripting News yet or micro.blog (I plan to post something there too).

**Comment by colin-walker** [comment]
I'm going to be posting about it today as well.

**Comment by colin-walker** [comment]
@scripting I see that Kev Quirk's is listed twice as well.

**Comment by scripting** [comment]
How to view the OPML behind each blogroll.

![image](https://github.com/scripting/opml.org/assets/1686843/fb60a730-094b-44a1-829e-2b48662ab68f)

**Comment by scripting** [comment]
Shortcut to a specific blogroll.

1. Click on the list in the left panel.
2. Copy the URL from the address bar.
3. Bookmark the URL or send to a friend.

An [example](https://browse.blogroll.social/?blogrollUrl=https%3A%2F%2Fcolinwalker.blog%2Ffeeds.opml&blogrollTitle=Colin%20Walker%27s%20readroll).

**Comment by manton** [comment]
Looking good. One minor typo: "it tooks a surprisingly long time"

As more blogrolls are found, it might be interesting to have a special section at the top, something like "5 blogrolls and 15 blogs found in the last month". Something to highlight that it's discovering new blogs. Just an idea.

**Comment by scripting** [comment]
I hooked up the View in FeedLand command in the popup menu in the blogroll.

When you choose the command, you'll switch into zero.blogroll.social (I know it's a weird name, probably will change), and view the river of news for that blogroll.

![image](https://github.com/scripting/opml.org/assets/1686843/1511bd2a-a3d8-44dc-ad74-01dda71ac8c4)

**Comment by scripting** [comment]
@manton -- good to see you here!

I doubt this is going to be the final form of the blogroll browser, or if a blogroll browser even makes sense.

It's just something I threw together quickly to get an idea of how much is going on here.

And by having this browser here, hopefully it will cause people to do more with their blogrolls, and this is just the first of many ways of navigating the network of blogrolls. 

It's sort of like the [coral reef](http://scripting.com/stories/2007/04/28/twitterAsCoralReef.html) concept. I don't have much of a desire to run this long term, but I figured if I didn't do it, it would be a long time coming.

**Comment by scripting** [comment]
BTW, @colin-walker -- 

I know View List in FeedLand doesn't work with your list.

I think it's probably due to the extra level of nesting in the outline, but I haven't been able to get to that place in the debugger to see what FL does with it. 

I want you to know it's on my list.

**Comment by colin-walker** [comment]
@scripting I can remove the nesting if it's not strictly valid.

**Comment by scripting** [comment]
@colin-walker — it’s totally valid to have nesting.

you could try removing the nesting just to help me see if that’s the problem.

**Comment by colin-walker** [comment]
@scripting Done.

**Comment by scripting** [comment]
@colin-walker --

i stepped through the process of feedland processing your list and it all worked as it's supposed to. i hate it when that happens. 

in any case right now we've got all your feeds. 

https://zero.blogroll.social/?readinglist=https%3A%2F%2Fcolinwalker.blog%2Ffeeds.opml

i'm going to have to come up with another reason this wasn't working, but we know there's nothing wrong with your list, and it probably didn't matter that you had an extra level in there, but for now, don't change what it does.

**Comment by scripting** [comment]
@colin-walker -- re your [blog post](https://colinwalker.blog/blog/?date=2024-06-26) which I just saw. 

I am not using source:blogroll, I found that it wasn't widely supported, but the <link> element we defined for the HTML page was.

So my crawler uses the htmlUrl attribute in the subscription list, and then reads the HTML and uses that link to find the blogroll OPML file.

**Comment by colin-walker** [comment]
Thanks. Corrected.

**Comment by scripting** [comment]
@colin-walker — to be clear I did not find the problem. I’m going to do some more debugging this morning.

**Comment by scripting** [comment]
I  found a big source of problems in the back-end of the Browser app.

https://github.com/scripting/feedlandInstall/issues/60

The FeedLand instance is now running more smoothly.

**Comment by scripting** [comment]
@manton 

how to find the new blogrolls.

https://zero.blogroll.social/?readinglists=davewiner

click on the Created column, to sort in order of when they were added

i didn't think of this at first. i have to remember we've got a really powerful backup server running here.

**Comment by scripting** [comment]
Cross-posted on micro.blog and scripting.com.

https://dave.micro.blog/2024/06/28/a-blogroll-lab.html

http://scripting.com/2024/06/28/170235.html

Dave

**Comment by scripting** [comment]
There's a new version of the [blogroll browser](https://browser.blogroll.social/) this morning.

1. Each item links to the OPML and HTML files it came from.
2. There's a menubar where more commands will appear.
3. The display should be less jittery as I tuned up the CSS a bit. 

![image](https://github.com/scripting/opml.org/assets/1686843/c3fe4f75-f353-4d8a-af91-d61c39a58b53)

**Comment by scripting** [comment]
### Three new commands

In the [Blogroll Browser](https://browse.blogroll.social/) menu, you will see three new commands.

1. [JSONified data](https://browse.blogroll.social/getdata) -- a list of blogrolls, each with an id and the id of their parent, the blogroll they were first discovered in.
2. [View graph in OPML](https://browse.blogroll.social/getgraphoutline) -- the data, organized in an outline hierarchy.
3. [View graph in Drummer](https://drummer.land/?url=https://browser.blogroll.social/getblogrolloutline) -- the outline viewed in the Drummer outliner.

This is a revisiting of BlogTree, an early community builder in the blogging community which organized blogs based on which community they rose out of. This was my favorite app because it was honest and made a really important statement how we were building communities of communities.

So this was an obvious next step.

**Comment by scripting** [comment]
One more fix/feature.

I didn't like how long the URLs were that we generate, so I shortened them to use the ID of the current blogroll.

So this will link to @colin-walker's blogroll.

https://browse.blogroll.social/?id=2

Much neater than what was there before. :smile:

**Comment by manton** [comment]
Any ideas where we should go from here? I'm wondering if we can learn anything from how Bluesky has rolled out their [Starter Parks](https://bsky.social/about/blog/06-26-2024-starter-packs). Starter Parks are effectively like a blogroll — a list of users to recommend to others. I think in Micro.blog we can do more, but not exactly sure where to take it next.

**Comment by scripting** [comment]
Manton -- glad you asked this question. 

And thanks for your interpretation of what Blue Sky did with Starter Packs. I didn't understand that. 

Here's what I think the potential of this is -- we're hoping to bootstrap the social graph of the blogosphere. 

That's why I used the terminology I used in the features I released yesterday.

If we can associate a subscription list with a feed, and view the feed as a person, we've got the same thing going as you noted they're doing with Bluesky. 

I think we should iterate over making it easier and easier to build blogrolls or readinglists or social-graph-nodes whatever we call them. But! -- don't go as far as Twitter-like systems have gone -- I am not a believer in blogs turning into discussion groups (like this one) because that topology always flames out, never fails to, and then you need moderation. I think the puzzle is to define a social graph that has easily-edited connections that are not likely to flame out, because the flaming has no power so people are less likely to do it. (I think most flaming is spam, trying to get attention, to increase power. In other words, spam.)

I also think [micro.blog](https://micro.blog) is a great lab to experiment with, for a variety of reasons. I built [FeedLand](http://feedland.org/) to be a place to manage these connections, and that goes back to the decision to use OPML, so that editing these groupings would easy and powerful  and there would be lots of competition. DId you know that OPML is widely supported in the Tools For Thought world? Not as widely as I would like. But the way you get that going is by presenting a sexy use-case they can't get to any other way. :smile:

Anyway -- this obviously will be a blog post on scripting.com before too long. :smile:

And Manton, thanks for working on this stuff. There would be no one to discuss this with if it weren't for you.

**Comment by scripting** [comment]
BTW @manton -- at another level -- i don't know where we go from exactly here.

We aren't getting new blogrolls in this little network, so as long as that's true, there's no reason to do more.

I don't think this UI is the browser. So in other words, I don't know what the next thing is, but I did this experiment in the hope it would give me ideas.

**Comment by scripting** [comment]
Also I think the JSON readout is the most interesting.

https://browse.blogroll.social/getdata

Dave

**Comment by scripting** [comment]
One thing I could do is link to rivers for each blogroll.

https://zero.blogroll.social/?readinglistnews=https%3A%2F%2Fcolinwalker.blog%2Ffeeds.opml

That's the news from @colin-walker's blogroll.

**Comment by scripting** [comment]
I'd like people to look at the blogroll as a feed reader.

I use my own regularly, by putting a feed in the blogroll, it gives me quick access to their posts, outside of a feed reader.

Where are good places to put the blogroll beyond the home page of your blog, which is a good place because you probably have a quick way to get to your blog home page. For me it's the Home button in the chrome of my browser.

I want feed reading to escape the feed reader.

Or to have a feed reader that's Twitter-like.

**Comment by colin-walker** [comment]
> BTW @manton -- at another level -- i don't know where we go from exactly here.
> 
> We aren't getting new blogrolls in this little network, so as long as that's true, there's no reason to do more.

It's hard to get adoption for stuff that requires a bit of work. Full credit to @manton for working on this but I feel many on micro.blog use the timeline as a quasi-Twitter (and put more emphasis on that than their blog) and that's their social element. They have no need or desire to build an extra "network" via something like blogrolls.

It's so much easier to just let the big sites do all the work.

There's no doubt that blogging has had something of a resurgence in recent years but it doesn't enjoy the same status as it used to.

The code for "Links" may still be present in WordPress Core but that it was hidden by default speaks volumes about the changing attitude to blogging.

I certainly see the connection between blogrolls and Bluesky's Starter Packs. They are both jumping off points — start here and build. Let's face it, that's what blogrolls have _always_ been. The problem is, so many bought into the "RSS is dead" narrative and, with browsers removing the functionality to expose and easily subscribe to feeds, it's harder to get people started than it should be.

**Comment by colin-walker** [comment]
> One thing I could do is link to rivers for each blogroll.
> 
> https://zero.blogroll.social/?readinglistnews=https%3A%2F%2Fcolinwalker.blog%2Ffeeds.opml
> 
> That's the news from @colin-walker's blogroll.
> 

😊 Just like my /reader page.

**Comment by scripting** [comment]
With that I guess this thread is done. 

I’m not giving up on the project, and I guess the few weeks I put into this was a waste and not appreciated. I can’t believe after all this time there are people still willing to say out loud the pernicious slandering of RSS by the VCs. I guess it was good at extinguishing hope that we could do this for ourselves. But saying it in this thread, that was over the top.

**Comment by manton** [comment]
Catching up on the thread… I think this was worthwhile and I still want to do more with blogrolls. I made a couple improvements in Micro.blog last week so that people can include a bit of "about" text for each blog for why they recommended it.

To @colin-walker's point about the social timeline vs. blogrolls, I think that's okay. In Micro.blog we called the feature at a high level "Recommendations" because it's like a subset of everyone you might be following. It's the top dozen or so people you really want to recommend that others check out.

What's next? I'd like to do something to make a link to a blogroll more visible. For example, on Bluesky when you share a Starter Pack, you get a nice preview of what someone is going to get if they click on it. I think we could do the same thing here, to encourage someone to share a link to their blogroll on social media.

**Comment by scripting** [comment]
@manton -- that's the challenge -- visible places to post the lists.

i think to do that we'll need to have a UI very much like twitter, but with feeds. 

it would have to be such a clone that people get the idea, that there's nothing magic about what twitter does.

and of course replies would be limited by what RSS etc can do with them.

which to me, is something i'd like to try. so i know i'm casting ideas into the wind, and people can link to me, but not attach themselves to my flow.

that's the end of spam, and changes how ideas flow.

still waiting to try that. ;-)

**Comment by scripting** [comment]
BTW -- I was wondering if someone would volunteer to keep an eye on the new blogrolls showing up here. 

the engine will keep running, and it's possible over time there may be some interesting innovations showing up here.

https://browse.blogroll.social/

remember this is based entirely on open formats, opml and feeds -- so it's not limited to what I or Manton do, anyone can create in this space.
