### ISSUE TITLE
validator.opml.org says "not a XML file", several XML validators say "File OK"

### ISSUE THREAD

**Issue by Kratorator** [scripting/opml.org#6]
Hi,

Just like the title says. I attach an example file generated from Omnioutliner 3.9 for IOS
[Document.zip](https://github.com/scripting/opml.org/files/9462111/Document.zip)

In advance, thanks for help.

K.

**Comment by scripting** [comment]
I uploaded your file and ran it through the validator and it says it's valid OPML.

http://validator.opml.org/?url=http://scripting.com/publicfolder/tmp/test2.opml

**Comment by scripting** [comment]
You might want to check out http://drummer.scripting.com/ -- my latest outliner.

**Comment by Kratorator** [comment]
Sorry man, I don't do social media, I don't do online apps, and I don't 
do the cloud.

If you ever release a fully offline version, count me in.

Ciao,

Christian

**Comment by scripting** [comment]
Yup that's what I use, it's called Electric Drummer.

http://docserver.scripting.com/drummer/electricDrummer.opml

And btw -- you're not doing me any favors by using it, you said you loved ThinkTank, and that's what this is, only many years later and much improved. And the cost is zero.

Now this thread is closed -- it's not for support for products, or helping people get their files on the web. ;-)
