### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by mincerafter42** [scripting/opml.org#7]
- <http://opml.org/spec2.opml> links to <http://support.opml.org/basicOutlining>, a page which returns a 404.
- <http://opml.org/history/aboutOpml11.opml> In The Original Post, there are several `<`s which should be `&lt;`s; this causes the text such as `<cloud>` and `<head>` to be invisible.

**Comment by scripting** [comment]
@mincerafter42 -- thanks for these notes, I believe I have fixed both.
